import './style.scss'
import {Roboto} from 'next/font/google'
import React from "react";
import {Providers} from "@/app/store/provider";
import Context from "@/app/hoc/Context";
import {Footer} from "@/widgets/footer";
import {Header} from "@/widgets/header";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
            <Providers>
                <Context>
                    <Header/>
                        <main>
                            {children}
                        </main>
                    <Footer/>
                </Context>
            </Providers>
        </body>
        </html>
    )
}
