// // RootLayout.tsx
// 'use client'
// import { Providers } from '@/app/store/provider';
// import { Header } from '@/widgets/header';
// // import { Footer } from '@/widgets/footer';
// import React from 'react';
// import { Lato } from 'next/font/google';
// import './style.scss';
//
// // import { Metadata } from 'next';
//
// const lato = Lato({ weight: '400', subsets: ['latin'] });
//
// // export const metadata: Metadata = {
// //     title: 'Next App',
// //     description: 'Generated by create next app',
// // };
//
// const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
//
//     return (
//         <html lang="en">
//         <body className={lato.className}>
//         <Providers>
//             <Header />
//             {children}
//             <Footer />
//         </Providers>
//         </body>
//         </html>
//     );
// };
//
// export default RootLayout;

'use client'
//
//
// import {Providers} from "@/app/store/provider";
// import {Header} from "@/widgets/header";
// import {Footer} from "@/widgets/footer";
//
// const RootLayout = ({ children }: {children: React.ReactNode}) => {
//     return (
//         <>
//             <html lang="en">
//             <body>
//                 <Providers>
//                     <Header />
//                     {children}
//                     <Footer />
//                 </Providers>
//             </body>
//             </html>
//         </>
//     );
// };
//
// export default RootLayout;

import { FC } from 'react';
import { Providers } from '@/app/store/provider';
import { Header } from '@/widgets/header';
import { Footer } from '@/widgets/footer';
import { useRouter } from 'next/navigation';


interface RootLayoutProps {
    children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
    // const router = useRouter();
    //
    // // Если пользователь не аутентифицирован, перенаправляем его на страницу входа
    // if (!isAuthenticated()) {
    //     router.push('/');
    // }

    return (
        <>
            <html lang="en">
            <body>
            <Providers>
                <Header />
                {children}
                <Footer />
            </Providers>
            </body>
            </html>
        </>
    );
};

export default RootLayout;